# Generated by Django 6.0.5 on 2026-06-03 11:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSNMPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('enabled', models.BooleanField(default=True)),
                ('snmp_version', models.CharField(default='2c', max_length=4)),
                ('port', models.PositiveIntegerField(default=161)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('auth_protocol', models.CharField(blank=True, default='none', max_length=10)),
                ('auth_key', models.CharField(blank=True, max_length=255)),
                ('priv_protocol', models.CharField(blank=True, default='none', max_length=10)),
                ('priv_key', models.CharField(blank=True, max_length=255)),
                ('timeout', models.FloatField(default=2.0)),
                ('retries', models.PositiveSmallIntegerField(default=1)),
                ('target_override', models.CharField(blank=True, max_length=255)),
                ('default_ethernet_type', models.CharField(blank=True, max_length=50)),
                ('skip_loopback_ips', models.BooleanField(default=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_config', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'device SNMP configuration',
                'verbose_name_plural': 'device SNMP configurations',
                'ordering': ('device',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
