# Generated by Django 6.0.5 on 2026-06-03 11:59

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_snmp_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('mode', models.CharField(default='compare', max_length=20)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('interfaces_created', models.PositiveIntegerField(default=0)),
                ('interfaces_updated', models.PositiveIntegerField(default=0)),
                ('interfaces_existing', models.PositiveIntegerField(default=0)),
                ('interfaces_ignored', models.PositiveIntegerField(default=0)),
                ('ips_created', models.PositiveIntegerField(default=0)),
                ('ips_existing', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_sync_runs', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SNMP sync run',
                'verbose_name_plural': 'SNMP sync runs',
                'ordering': ('-created',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
