# Generated by Django 6.0.5 on 2026-06-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_snmp_sync', '0002_syncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SyncRunObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_objects', to='netbox_snmp_sync.syncrun')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
