# Generated by Django 6.0.5 on 2026-06-04 07:52

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_snmp_sync', '0003_syncrun_reverted_syncrunobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sync_interval_hours', models.PositiveIntegerField(default=0)),
                ('update_existing', models.BooleanField(default=False)),
                ('set_mac_address', models.BooleanField(default=True)),
                ('skip_loopback_ips', models.BooleanField(default=True)),
                ('write_vlans', models.BooleanField(default=False)),
                ('create_vlans', models.BooleanField(default=False)),
                ('snmp_version', models.CharField(default='2c', max_length=4)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=255)),
                ('snmp_timeout', models.FloatField(default=2.0)),
                ('snmp_retries', models.PositiveSmallIntegerField(default=1)),
                ('default_ethernet_type', models.CharField(default='1000base-t', max_length=50)),
                ('history_keep_days', models.PositiveIntegerField(default=90)),
                ('history_keep_count', models.PositiveIntegerField(default=1000)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SNMP Sync settings',
                'verbose_name_plural': 'SNMP Sync settings',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
