# Generated by Django 6.0.5 on 2026-06-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0004_snmpsyncconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='default_ethernet_type',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='skip_loopback_ips',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='snmp_community',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='snmp_port',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='snmp_retries',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='snmp_timeout',
        ),
        migrations.RemoveField(
            model_name='snmpsyncconfig',
            name='snmp_version',
        ),
    ]
