# Generated by Django 6.0.5 on 2026-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0005_remove_snmpsyncconfig_default_ethernet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_test_message',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_test_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_tested_ok',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
