# Generated by Django 6.0.5 on 2026-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0006_devicesnmpconfig_last_test_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpsyncconfig',
            name='sync_at_hours',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
