# Generated by Codex on 2026-06-05

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone

SCHEDULE_SPREAD_MAX_MINUTES = 15


def _parse_hours(raw):
    out = set()
    for part in str(raw or "").replace(" ", "").split(","):
        if part.isdigit() and 0 <= int(part) <= 23:
            out.add(int(part))
    return out


def _next_sync_at(enabled, hours, allowed_hours, reference, spread_offset=None):
    spread_offset = spread_offset or timedelta()
    if not enabled or (hours <= 0 and not allowed_hours):
        return None
    if allowed_hours:
        local_ref = timezone.localtime(reference)
        candidates = []
        for hour in allowed_hours:
            candidate = local_ref.replace(hour=hour, minute=0, second=0, microsecond=0)
            if candidate <= local_ref:
                candidate += timedelta(days=1)
            candidates.append(candidate)
        return min(candidates) + spread_offset
    return reference + timedelta(hours=hours) + spread_offset


def _spread_window(hours, allowed_hours):
    if hours <= 0 and not allowed_hours:
        return timedelta()
    if allowed_hours:
        return timedelta(minutes=SCHEDULE_SPREAD_MAX_MINUTES)
    return timedelta(minutes=min(SCHEDULE_SPREAD_MAX_MINUTES, max(hours * 60 - 1, 0)))


def _spread_offsets(count, spread_window):
    if count <= 1 or spread_window <= timedelta():
        return [timedelta() for _ in range(max(count, 0))]
    step = spread_window / (count - 1)
    return [step * index for index in range(count)]


def seed_schedule_state(apps, schema_editor):
    DeviceSNMPConfig = apps.get_model('netbox_snmp_sync', 'DeviceSNMPConfig')
    SNMPSyncConfig = apps.get_model('netbox_snmp_sync', 'SNMPSyncConfig')
    SyncRun = apps.get_model('netbox_snmp_sync', 'SyncRun')

    cfg = SNMPSyncConfig.objects.first()
    hours = cfg.sync_interval_hours if cfg else 0
    allowed_hours = _parse_hours(cfg.sync_at_hours if cfg else "")
    now = timezone.now()
    configs = list(DeviceSNMPConfig.objects.all().order_by('device__name', 'pk'))
    enabled_configs = [config for config in configs if config.enabled]
    offsets = _spread_offsets(len(enabled_configs), _spread_window(hours, allowed_hours))
    offsets_by_pk = {config.pk: offset for config, offset in zip(enabled_configs, offsets)}

    for config in configs:
        latest = SyncRun.objects.filter(device_id=config.device_id).order_by('-created').first()
        if latest:
            config.last_sync_at = latest.created
            config.last_sync_status = latest.status
            config.last_sync_message = (latest.message or "")[:255]
        config.next_sync_at = _next_sync_at(
            config.enabled, hours, allowed_hours, now,
            spread_offset=offsets_by_pk.get(config.pk, timedelta()),
        )
        config.save(update_fields=(
            'last_sync_at', 'last_sync_status', 'last_sync_message', 'next_sync_at',
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0007_snmpsyncconfig_sync_at_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='consecutive_sync_failures',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_sync_message',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='last_sync_status',
            field=models.CharField(
                blank=True,
                choices=[('ok', 'OK'), ('failed', 'Failed')],
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(seed_schedule_state, migrations.RunPython.noop),
    ]
