# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0008_devicesnmpconfig_schedule_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='sync_job_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='sync_queued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
