# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0009_devicesnmpconfig_sync_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='sync_interval_hours',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Per-device hours between automatic syncs. Blank = use global setting; 0 disables interval sync for this device unless Sync at hours is set.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='devicesnmpconfig',
            name='sync_at_hours',
            field=models.CharField(
                blank=True,
                help_text='Per-device sync hours (0-23, comma-separated). Blank = use global setting unless a per-device interval is set.',
                max_length=64,
                verbose_name='Sync at hours',
            ),
        ),
    ]
