# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_snmp_sync', '0010_devicesnmpconfig_schedule_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpsyncconfig',
            name='sync_job_timeout_seconds',
            field=models.PositiveIntegerField(
                default=300,
                help_text='Maximum runtime for the SNMP collection phase of a background sync job. 0 disables this guard.',
            ),
        ),
    ]
